name: Android Build Compiler Psych Online

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"

jobs:
  Build:
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Android-NORMAL
            os: ubuntu-latest
            setupCommand: sh ./setup/unix-alter.sh
            buildArgs: "android -ONLY_ARM64 -final"
            artifactName: androidBuild-Astra
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            doCache: "YES"

          - name: Windows-NORMAL
            os: windows-latest
            setupCommand: "setup/windows.bat"
            buildArgs: "windows -DofficialBuild -final"
            artifactName: windowsBuild-x86_64
            artifactPath: "PsychOnline-Windows.zip"
            doCache: "YES"

    uses: ./.github/workflows/build.yml
    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      setupCommand: ${{ matrix.setupCommand }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}
      doCache: ${{ matrix.doCache }}
    secrets: inherit

  Release:
    needs: Build
